name: pint

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run pint
        uses: prymitive/pint-action@v0.5-rc4
        with:
          token: ${{ github.token }}
          workdir: 'rules'
