name: pint

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - uses: actions/checkout@v3
        with:
          ref: prymitive-patch-1
          fetch-depth: 0

      - name: Run pint
        run: |
          curl -sLo pint.tar.gz https://github.com/cloudflare/pint/releases/download/v0.24.0/pint-0.24.0-linux-x86_64.tar.gz
          tar -xf pint.tar.gz
          ./pint-linux-amd64 --log-level=debug ci
        env:
          GITHUB_AUTH_TOKEN: ${{ github.token }}
