name: pint

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.4

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run pint
        run: |
          git checkout ${{ env.GITHUB_REF_NAME }}
          curl -sLo pint.tar.gz https://github.com/cloudflare/pint/releases/download/v0.24.0/pint-0.24.0-linux-x86_64.tar.gz
          tar -xf pint.tar.gz
          ./pint-linux-amd64 --log-level=debug ci
        env:
          GITHUB_AUTH_TOKEN: ${{ github.token }}
